### PR TITLE
Refactoring to improve the project structure

### PR DESCRIPTION
**Pull request by faelperetta**
The new structure let the project easier to understand and read.
- Global variables were removed
- Services e controllers were created in order to separate the responsabilities
- Refactoring to user javascript array forEach and filter

### CODE REVIEW

**Comment by PauloLuan** [comment]
Thanks for your contribution, I really appreciate that. Could you see this PR please @pedro-hos

**Comment by pedro-hos** [comment]
great, thanks @faelperetta . It is a william's project. Could you see this PR please @jesuino

**Comment by jesuino** [comment]
+1
I will check this week and provide a feedback, thanks @faelperetta

**Comment by jesuino** [comment]
Thank you so much, @faelperetta - unfortunately it took more than one week to review this - however I will merge now - really appreciate your contribution, Balanco is an important project for Sao Paulo state cities - soon we will make integration with Repasse

**Pull request merged**
